### ISSUE TITLE
Create front end UI for submitting palettes of new city

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg-palette#54]
- [x] Create page for inputting country, city and lines info #55 
- [x] Generate GitHub issue template when user clicks 'Submit' button #56 
- [x] Allow user to copy palette info entered earlier #77 
- [x] Add input validation #75 
- [x] Display input validation result in submit modal and allow user to open PR anyway #78
